Repository Re-Career/Re-Career, pull requests merged in 2025-08, with the labels that each got.

#19 Feat: /positions 관련 api 추가
  backend/src/main/java/com/recareer/backend/config/SecurityConfig.java
  backend/src/main/java/com/recareer/backend/mentor/repository/MentorRepository.java
  backend/src/main/java/com/recareer/backend/news/controller/NewsController.java
  backend/src/main/java/com/recareer/backend/news/dto/NewsDto.java
  backend/src/main/java/com/recareer/backend/news/entity/News.java
  backend/src/main/java/com/recareer/backend/news/repository/NewsRepository.java
  backend/src/main/java/com/recareer/backend/news/service/NewsService.java
  backend/src/main/java/com/recareer/backend/position/controller/PositionController.java
  backend/src/main/java/com/recareer/backend/position/dto/PositionDto.java
  backend/src/main/java/com/recareer/backend/position/dto/PositionResponsibilitiesDto.java
  backend/src/main/java/com/recareer/backend/position/dto/PositionSimpleDto.java
  backend/src/main/java/com/recareer/backend/position/dto/PositionWithResponsibilitiesDto.java
  backend/src/main/java/com/recareer/backend/position/dto/RegionPositionRequestDto.java
  backend/src/main/java/com/recareer/backend/position/dto/RegionPositionResponseDto.java
  backend/src/main/java/com/recareer/backend/position/entity/Position.java
  backend/src/main/java/com/recareer/backend/position/entity/PositionResponsibilities.java
  backend/src/main/java/com/recareer/backend/position/entity/PositionResponsibilityMap.java
  backend/src/main/java/com/recareer/backend/position/repository/PositionRepository.java
  backend/src/main/java/com/recareer/backend/position/repository/PositionResponsibilitiesRepository.java
  backend/src/main/java/com/recareer/backend/position/repository/PositionResponsibilityMapRepository.java
  backend/src/main/java/com/recareer/backend/position/service/PositionService.java
Labels: enhancement

#15 성향 태그 기반 멘토 매칭 기능 추가
  backend/build.gradle
  backend/src/main/java/com/recareer/backend/availableTime/entity/AvailableTime.java
  backend/src/main/java/com/recareer/backend/availableTime/repository/AvailableTimeRepository.java
  backend/src/main/java/com/recareer/backend/config/SecurityConfig.java
  backend/src/main/java/com/recareer/backend/mentor/controller/MentorController.java
  backend/src/main/java/com/recareer/backend/mentor/dto/MentorListResponseDto.java
  backend/src/main/java/com/recareer/backend/mentor/repository/MentorRepository.java
  backend/src/main/java/com/recareer/backend/mentor/service/MentorService.java
  backend/src/main/java/com/recareer/backend/mentor/service/MentorServiceImpl.java
  backend/src/main/java/com/recareer/backend/reservation/repository/ReservationRepository.java
  backend/src/main/java/com/recareer/backend/sessionRecord/entity/SessionRecord.java
  backend/src/main/java/com/recareer/backend/sessionRecord/repository/SessionRecordRepository.java
  backend/src/main/java/com/recareer/backend/user/repository/UserPersonalityTagRepository.java
  backend/src/test/java/com/recareer/backend/mentor/controller/MentorControllerTest.java
  backend/src/test/java/com/recareer/backend/mentor/service/MentorServiceTest.java
Labels: enhancement

#23 동적 CORS 설정 추가
  backend/src/main/java/com/recareer/backend/config/SecurityConfig.java
Labels: bug

#25 멘토 API 업데이트
  backend/src/main/java/com/recareer/backend/mentor/controller/MentorController.java
  backend/src/main/java/com/recareer/backend/mentor/entity/Mentor.java
  backend/src/main/java/com/recareer/backend/mentor/entity/MentoringType.java
  backend/src/main/java/com/recareer/backend/mentor/service/MentorService.java
  backend/src/main/java/com/recareer/backend/mentor/service/MentorServiceImpl.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
  backend/src/test/java/com/recareer/backend/mentor/controller/MentorControllerTest.java
  backend/src/test/java/com/recareer/backend/mentor/service/MentorServiceTest.java
Labels: enhancement, invalid

#29 🐛 Fix: CORS 허용 도메인 추가
  backend/src/main/java/com/recareer/backend/config/SecurityConfig.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
Labels: bug

#30 🛠️ Fix: CORS 설정 수정
  backend/src/main/java/com/recareer/backend/config/SecurityConfig.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
Labels: bug

#42 32 backend connect api to frontend
  backend/src/main/java/com/recareer/backend/mentor/controller/MentorController.java
  backend/src/main/java/com/recareer/backend/mentor/dto/FilterOptionDto.java
  backend/src/main/java/com/recareer/backend/mentor/dto/FilterOptionsResponseDto.java
  backend/src/main/java/com/recareer/backend/mentor/dto/MentorCard.java
  backend/src/main/java/com/recareer/backend/mentor/dto/MentorSearchResponse.java
  backend/src/main/java/com/recareer/backend/mentor/service/MentorService.java
  backend/src/main/java/com/recareer/backend/mentor/service/MentorServiceImpl.java
  backend/src/main/java/com/recareer/backend/mentoringRecord/controller/MentoringRecordController.java
  backend/src/main/java/com/recareer/backend/mentoringRecord/dto/MentoringRecordListResponseDto.java
  backend/src/main/java/com/recareer/backend/mentoringRecord/dto/MentoringRecordRequestDto.java
  backend/src/main/java/com/recareer/backend/mentoringRecord/dto/MentoringRecordResponseDto.java
  backend/src/main/java/com/recareer/backend/mentoringRecord/entity/MentoringRecord.java
  backend/src/main/java/com/recareer/backend/mentoringRecord/entity/MentoringRecordStatus.java
  backend/src/main/java/com/recareer/backend/mentoringRecord/repository/MentoringRecordRepository.java
  backend/src/main/java/com/recareer/backend/mentoringRecord/service/AudioTranscriptionService.java
  backend/src/main/java/com/recareer/backend/mentoringRecord/service/AudioTranscriptionServiceImpl.java
  backend/src/main/java/com/recareer/backend/mentoringRecord/service/MentoringRecordService.java
  backend/src/main/java/com/recareer/backend/mentoringRecord/service/MentoringRecordServiceImpl.java
  backend/src/main/java/com/recareer/backend/reservation/controller/ReservationController.java
  backend/src/main/java/com/recareer/backend/reservation/dto/ReservationCancelRequestDto.java
  backend/src/main/java/com/recareer/backend/reservation/dto/ReservationListResponseDto.java
  backend/src/main/java/com/recareer/backend/reservation/dto/ReservationRequestDto.java
  backend/src/main/java/com/recareer/backend/reservation/dto/ReservationResponseDto.java
  backend/src/main/java/com/recareer/backend/reservation/dto/ReservationUpdateRequestDto.java
  backend/src/main/java/com/recareer/backend/reservation/entity/Reservation.java
  backend/src/main/java/com/recareer/backend/reservation/entity/ReservationStatus.java
  backend/src/main/java/com/recareer/backend/reservation/repository/ReservationRepository.java
  backend/src/main/java/com/recareer/backend/reservation/service/ReservationService.java
  backend/src/main/java/com/recareer/backend/reservation/service/ReservationServiceImpl.java
  backend/src/main/java/com/recareer/backend/session/controller/SessionController.java
  backend/src/main/java/com/recareer/backend/session/dto/SessionDetailResponseDto.java
  backend/src/main/java/com/recareer/backend/sessionRecord/entity/SessionRecord.java
  backend/src/main/java/com/recareer/backend/sessionRecord/repository/SessionRecordRepository.java
  backend/src/test/java/com/recareer/backend/mentor/controller/MentorControllerTest.java
  backend/src/test/java/com/recareer/backend/mentor/controller/MentorDetailControllerTest.java
  backend/src/test/java/com/recareer/backend/mentor/service/MentorServiceTest.java
  backend/src/test/java/com/recareer/backend/mentoringRecord/controller/MentoringRecordControllerTest.java
  backend/src/test/java/com/recareer/backend/mentoringRecord/service/MentoringRecordServiceTest.java
  backend/src/test/java/com/recareer/backend/reservation/controller/ReservationControllerTest.java
  backend/src/test/java/com/recareer/backend/reservation/service/ReservationServiceImplTest.java
Labels: bug, enhancement

#46 /session api 수정
  backend/src/main/java/com/recareer/backend/config/SecurityConfig.java
  backend/src/main/java/com/recareer/backend/mentor/repository/MentorRepository.java
  backend/src/main/java/com/recareer/backend/session/controller/SessionController.java
  backend/src/main/java/com/recareer/backend/session/dto/SessionCreateResponseDto.java
  backend/src/main/java/com/recareer/backend/session/dto/SessionDetailResponseDto.java
  backend/src/main/java/com/recareer/backend/session/dto/SessionRequestDto.java
  backend/src/main/java/com/recareer/backend/session/dto/SessionResponseDto.java
  backend/src/main/java/com/recareer/backend/session/dto/SessionUpdateRequestDto.java
  backend/src/main/java/com/recareer/backend/session/dto/SessionUpdateResponseDto.java
  backend/src/main/java/com/recareer/backend/session/service/SessionService.java
  backend/src/main/java/com/recareer/backend/session/service/SessionServiceImpl.java
Labels: bug, enhancement
